#theme: jekyll-theme-midnight
baseurl: "/jekyll-serif-theme/"
title: Elio Bastias 
description: Open Source Enthusiast 
            | Love to write elegant code 
            | Gopher, Python | DevOps | DBA
